defaults: &defaults
  host: localhost

development:
  database: db/eds_development.db
  adapter: sqlite3
  <<: *defaults

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgres
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...

test:
  database: db/eds_test.db
  adapter: sqlite3
  <<: *defaults

production:
  database: db/eds_production.db
  adapter: postgres
  <<: *defaults
